---
title: "Test Plots"
output: html_document
---

```{r}
library(tidyverse)
library(plotly)
library(deSolve)
source("helpers.R")
```

```{r}
install.packages("rjson")
```


```{r}
url = "https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json"
borders = rjson::fromJSON(file="https://raw.githubusercontent.com/johan/world.geo.json/master/countries.geo.json")
country_codes = read.csv("https://raw.githubusercontent.com/hoganj15/MMA_Assignment_Data/main/COVID/country_codes.csv") %>% rename(Country = name, Code = code, lat = latitude, lon = longitude, two_digit = country)
data = countries %>% group_by(Country) %>% filter(Date == max(Date))
data = left_join(data, country_codes, by = "Country")
data
```

```{r}
plot_ly(data = data, type = "choroplethmapbox", geojson = borders, locations = data$Code, z = data$Confirmed, colorscale="Viridis", zmin = 1000, zmax = 10000000, text = ~paste("<br>", "Total Cases:", data$Confirmed, "<br>", "Total Deaths:", data$Deaths), marker = list(line = list(width=0), opacity=0.75)) %>% 
    layout(mapbox = list(style = "open-street-map"), title = "Confirmed Cases Heat Map")
```

